function [effects_table, comparisons_table] = compareEffectSizes(reach_data, keyboard_data, fields, cond1, cond2, pairs, n_bootstraps, good_subs)
    % Inputs:
    % reach_data: The reach_avg_each struct
    % keyboard_data: The keyboard_avg_each struct
    % fields: Cell array of strings, e.g., {'mad', 'auc', 'kb_rt'}
    % cond1, cond2: Strings of conditions to compare, e.g., 'con', 'incon'
    % pairs: Cell array of cell arrays for comparisons, generated by nchoosek
    % n_bootstraps: Integer, e.g., 10000
    % good_subs: Vector containing the indices of valid participants

    %% 1. Master Indices & Storage
    num_valid = length(good_subs);
    master_boot_indices = randi(num_valid, num_valid, n_bootstraps);
    
    % Temporary structs to hold data for the pairwise step
    distributions = struct(); 
    actual_dzs_struct = struct();
    
    %% 2. Calculate Cohen's dz Distribution for Each Individual Field
    % Preallocate arrays for the table
    effect_names = strings(length(fields), 1);
    actual_dzs   = NaN(length(fields), 1);
    actual_diffs   = NaN(length(fields), 1);
    actual_diffs_SD   = NaN(length(fields), 1);
    ci_lowers    = NaN(length(fields), 1);
    ci_uppers    = NaN(length(fields), 1);
    
    for i = 1:length(fields)
        f = fields{i};
        
        % Extract data
        if startsWith(f, 'kb_')
            f_clean = strrep(f, 'kb_', '');
            data1 = keyboard_data.(f_clean)(1).(cond1)(good_subs);
            data2 = keyboard_data.(f_clean)(1).(cond2)(good_subs);
        else
            data1 = reach_data.(f)(1).(cond1)(good_subs);
            data2 = reach_data.(f)(1).(cond2)(good_subs);
        end
        
        % --- CALCULATE ACTUAL POINT ESTIMATE (ABSOLUTE VALUE) ---
        diff_actual = data1 - data2;
        actual_dz = abs(mean(diff_actual) / std(diff_actual));
        actual_dzs_struct.(f) = actual_dz;
        
        % --- RUN BOOTSTRAP ---
        dist = bootCohenDz(data1, data2, master_boot_indices);
        distributions.(f) = dist;
        
        % Store for table
        effect_names(i) = string(f);
        actual_dzs(i)   = actual_dz;
        actual_diffs(i) = mean(diff_actual); 
        actual_diffs_SD(i) = std(diff_actual);
        ci_lowers(i)    = prctile(dist, 2.5);
        ci_uppers(i)    = prctile(dist, 97.5);
    end
    
    % Generate and print Effects Table
    effects_table = table(effect_names,actual_diffs,actual_diffs_SD, actual_dzs, ci_lowers, ci_uppers, ...
        'VariableNames', {'Effect_Name','Actual Diff','SD(Act_Diff)', 'Actual_dz', 'CI_Lower', 'CI_Upper'});
    
    fprintf('\n--- Individual Effect Sizes (Absolute, 95%% CI) ---\n');
    disp(effects_table);
    
    %% 3. Calculate Comparisons Between Paired Effects
    % Preallocate arrays for the table
    comp_names     = strings(length(pairs), 1);
    actual_diffs   = NaN(length(pairs), 1);
    comp_ci_lowers = NaN(length(pairs), 1);
    comp_ci_uppers = NaN(length(pairs), 1);
    p_values       = NaN(length(pairs), 1);
    
    for i = 1:length(pairs)
        fA = pairs{i}{1};
        fB = pairs{i}{2};
        
        % --- DETERMINE WHICH EFFECT IS LARGER ---
        % This ensures the actual difference is always positive
        if actual_dzs_struct.(fA) >= actual_dzs_struct.(fB)
            larger_f = fA;
            smaller_f = fB;
        else
            larger_f = fB;
            smaller_f = fA;
        end
        
        % --- CALCULATE ACTUAL POINT DIFFERENCE ---
        actual_diff = actual_dzs_struct.(larger_f) - actual_dzs_struct.(smaller_f);
        
        % --- SUBTRACT DISTRIBUTIONS (Larger - Smaller) ---
        diff_dist = distributions.(larger_f) - distributions.(smaller_f);
        
        % Store for table
        comp_names(i)     = sprintf('%s_minus_%s', larger_f, smaller_f);
        actual_diffs(i)   = actual_diff;
        comp_ci_lowers(i) = prctile(diff_dist, 2.5);
        comp_ci_uppers(i) = prctile(diff_dist, 97.5);
        
        % Calculate 2-tailed p-value
        p_values(i) = min(sum(diff_dist > 0), sum(diff_dist < 0)) / n_bootstraps * 2;
    end
    
    % Generate and print Comparisons Table
    comparisons_table = table(comp_names, actual_diffs, comp_ci_lowers, comp_ci_uppers, p_values, ...
        'VariableNames', {'Comparison', 'Actual_Diff', 'CI_Lower', 'CI_Upper', 'P_Value'});
        
    fprintf('\n--- Pairwise Comparisons of Magnitudes (95%% CI) ---\n');
    disp(comparisons_table);
end

%% Helper Function (Encapsulated)
function [boot_dz] = bootCohenDz(data1, data2, boot_indices)
    differences = data1 - data2;
    boot_samples = differences(boot_indices);
    boot_means = mean(boot_samples, 1);
    boot_stds  = std(boot_samples, 0, 1);
    % Take the absolute value for the entire distribution!
    boot_dz    = abs(boot_means ./ boot_stds);
end