% Gives a table with the descriptive statistcs.
% print_title - to print before the results.
% data_title - title of each data var (e.g., {'con', 'incon'}).
% p_val - of test.
% ci - confidence intervals.
% stats - output of ttest(): tstat, df, sd. 
function outStatsTable = printStats(print_title, data1, data2, data_title, p_val, ci, stats)
    differ = data1 - data2;
    cohens_dz = mean(differ) / stats.sd;

    outStats = struct(...
        'name',string(print_title),...
        'con_avg',mean(data1),...
        'con_std',std(data1),...
        'incon_avg',mean(data2),...
        'incon_std',std(data2),...
        'diff_avg',mean(differ),...
        'diff_relative_std',std(differ) / mean(differ),...
        'tVal',stats.tstat,...
        'df',stats.df,...
        'pVal',p_val,...
        'CI_low',ci(1),...
        'CI_high',ci(2),...
        't_SD',stats.sd,...
        'cohens_d_z',cohens_dz...
        );

    outStatsTable = struct2table(outStats);
end