function [updatedStatsTable] = transferStatsToStatsTable(newStatsTable,oldTable)

arguments (Input)
    newStatsTable = [];
    oldTable = [];
end

arguments (Output)
    updatedStatsTable
end

    if(nargin<1)
        % return an empty table
            outStats = struct(...
        'name',[],...
        'con_avg',[],...
        'con_std',[],...
        'incon_avg',[],...
        'incon_std',[],...
        'diff_avg',[],...
        'diff_relative_std',[],...
        'tVal',[],...
        'df',[],...
        'pVal',[],...
        'CI_low',[],...
        'CI_high',[],...
        't_SD',[],...
        'cohens_d_z',[]...
        );

        updatedStatsTable = struct2table(outStats);
        return;
    end

    % Initialize the updatedStatsTable with the oldTable
    updatedStatsTable = oldTable;
    
    if(isempty(newStatsTable))
        return;
    end

    % Update the table with new statistics from newStatsStruct
    updatedStatsTable = [updatedStatsTable; newStatsTable];

end